### ISSUE TITLE
Is there any way to do conditional validation?

### ISSUE THREAD

**Issue by MocanuMarius** [vandium-io/joi-json#4]
Talking about the if then else style conditions from joi...for example if this field is valid then the next one is required.

**Comment by richardhyatt** [comment]
are you trying to do something like`.alternatives()` or using references with `.when()`?

**Comment by MocanuMarius** [comment]
Yes, something like this; 
`a: Joi.alternatives().when('b', { is: true, then: Joi.required() }),`

**Comment by koshuang** [comment]
+1, that would be very helpful :)
